//====================
// MARK: - Characters
//====================

//let TEAMNUMBER = 2

let TEAMNUMBER = 2

//let CHARACTERNUMBER = 3

let CHARACTERNUMBER = 3

//let FIGHTERLIFE = 100
//let WIZARDLIFE = 100
//let COLOSSUSLIFE = 120
//let DWARFLIFE = 80

let FIGHTERLIFE = 100
let WIZARDLIFE = 100
let COLOSSUSLIFE = 120
let DWARFLIFE = 80

let DEAD = 0

//=================
// MARK: - Weapons
//=================

// Balancing values:

//let SWORDDAMAGE = 10
//let STICKDAMAGEMIN = 5
//let STICKDAMAGEMAX = 15
//let FISTSDAMAGE = 8
//let AXEDAMAGE = 12
//let MACEDAMAGEMIN = 8
//let MACEDAMAGEMAX = 12
//let DAGGERDAMAGEMIN = 1
//let DAGGERDAMAGEMAX = 25
//let SPEARDAMAGEMIN = 5
//let SPEARDAMAGEMAX = 15

let SWORDDAMAGE = 10
let STICKDAMAGEMIN = 5
let STICKDAMAGEMAX = 15
let FISTSDAMAGE = 8
let AXEDAMAGE = 12
let MACEDAMAGEMIN = 8
let MACEDAMAGEMAX = 12
let DAGGERDAMAGEMIN = 1
let DAGGERDAMAGEMAX = 25
let SPEARDAMAGEMIN = 5
let SPEARDAMAGEMAX = 15
